apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: practica-cd
  name: practica-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practica-cd
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: practica-cd
    spec:
      containers:
      - name: java-app
        image: franco87/practica-ci:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
