
name: deploy release

on:
  repository_dispatch:
    types: [opened]

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Creating SSH tunnel
      run: |
        ssh mca@${{ secrets.TARGET_HOST }} -f -L 16443:localhost:16443 -N -o "StrictHostKeyChecking no"
    - name: Deploy
      uses: actions-hub/kubectl@master
      env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods