
name: deploy release

on:
  repository_dispatch:
    types: [build_application]

jobs:
  deployment:

    runs-on: ubuntu-latest

    services:
      ssh:
        image: ubuntu
        options: >-
          --entrypoint="ssh-add - $SSH_PRIVATE_KEY && ssh mca@$TARGET_HOST -L 16443:localhost:16443 -N -o \"StrictHostKeyChecking no\""
        ports:
          - 16443:16443
        env:
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: actions-hub/kubectl@master
      env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods