
name: deploy release

on:
  repository_dispatch:
    types: [build_application]

jobs:
  deployment:

    runs-on: ubuntu-latest

    services:
      ssh:
        image: busybox
        options: >-
          --entrypoint	"ssh mca@$TARGET_HOST -L 16443:localhost:16443 -N -o \"StrictHostKeyChecking no\""
        ports:
          - 16443:16443
        env:
          TARGET_HOST: ${{ secrets.TARGET_HOST }}


    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      uses: actions-hub/kubectl@master
      env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods