
name: deploy release

on:
  repository_dispatch:
    types: [build_application]

jobs:
  deployment:

    runs-on: ubuntu-latest

    services:
      ssh:
        image: franco87/ubuntu-ssh
        ports:
          - 16443:16443
        env:
          TARGET_HOST: ${{ secrets.TARGET_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ENTRYPOINT_CMD: "ssh-add - $SSH_PRIVATE_KEY && ssh mca@$TARGET_HOST -L 16443:localhost:16443 -N -o \"StrictHostKeyChecking no\""

    steps:
    - uses: actions/checkout@v2
    - name: set kubeconfig
      run: echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ${KUBECONFIG}
    - name: Deploy
      run: kubectl get pods