
name: deploy release

on:
  repository_dispatch:
    types: [deploy_application]

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ssh proxy
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
        chmod 400 /tmp/ssh_key
        ssh -i /tmp/ssh_key mca@${{ secrets.TARGET_HOST }} -f -L 16443:localhost:16443 -N -o "StrictHostKeyChecking no"
    - name: set kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > /tmp/kubeconfig
    - name: Deploy
      run: |
        kubectl --kubeconfig=/tmp/kubeconfig set image deployment/practica-cd java-app=${{ github.event.client_payload.new_image }}
    - name: Watch rolling update status
      run: |
        kubectl --kubeconfig=/tmp/kubeconfig rollout status -w deployment/practica-cd --timeout=60s
    - name: rollback
      if: ${{ failure() }}
      run: |
        kubectl --kubeconfig=/tmp/kubeconfig rollout undo -w deployment/practica-cd
        kubectl --kubeconfig=/tmp/kubeconfig rollout status -w deployment/practica-cd --timeout=60s