
name: deploy release

on:
  repository_dispatch:
    types: [build_application]

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ssh proxy
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
        ssh -i /tmp/ssh_key mca@${{ secrets.TARGET_HOST }} -f -L 16443:localhost:16443 -N -o "StrictHostKeyChecking no"
    - name: set kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > /tmp/kubeconfig
    - name: Deploy
      run: |
        kubectl --kubeconfig=/tmp/kubeconfig get pods